[package]
name = "chatgtp-prep-data"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gitlab = "0.1506.0"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1"
